### ISSUE TITLE
An error in the article regarding "mentioning" of intermediate targets for GNU Make?

### ISSUE THREAD

**Issue by amn** [albertnetymk/albertnetymk.github.io#1]
Hi Albert,

Apologies in advance for seemingly digging up old Internet history, but for the sake of correctness... I stumbled upon http://albertnetymk.github.io/2015/06/12/makefile_chain_implicit_rules/ while diving into GNU Make and I believe the following sentence is wrong:

https://github.com/albertnetymk/albertnetymk.github.io/blob/6437361ffb2ea7af3272d01e2ec843c28ffca176/2015/06/12/makefile_chain_implicit_rules/index.html#L201

I also verified this empirically -- `main.o` _is_ removed by Make at the conclusion of invocation, as `main.out` is built. The crux of this is that merely mentioning the text `main.o` in actual shell invocation (must be `rm -f main.o ...` because there's no other mention of `main.o` there) that is part of a recipe isn't what GNU Make means with "mentioning". The latter covers only specifying a file as a target or a prerequisite, _not_ in, say, recipes. It's also not reasonable to expect Make to understand shell command lines to such a degree it may infer their meaning (_parsing_ them) while parsing a makefile.

Am I onto something here?

It's not a biggie, but since your pages are indexed and people (like me) read them, I thought getting to the common understanding here would be beneficial, however small the matter.

Good day,

**Comment by albertnetymk** [comment]
Sorry for the late reply. I didn't enable email notification for issues...

My original text was probably too misleading -- I was referring to the first Makefile. Hopefully clearer after the revision. Thank you for the feedback.
